from tkinter import *
import pickle
from tkinter import messagebox
import pandas as pd
from tkinter import ttk
t = Tk()
t.geometry("600x400+200+100")
t.resizable(False , False)
t.configure(background = "snow")
t.title("Banglore House Price Prediction")
def predict():
        model = pickle.load(open('model.pkl','rb'))
        val = pd.DataFrame([[a.get(), b.get(),c.get(),d.get()]], columns=['location','total_sqft','bath','bhk'])
        value = int(model.predict(val))
        l6 = Label(text = str(value) + 'Lakhs' ,font=("Arial Bold" ,10), bg='snow')
        l6.place(x= 270 , y= 320)


     
a = StringVar()
b = IntVar()
c = IntVar()
d = IntVar()  
l1 = Label(text ="Banglore House Price Prediction" , font=("Arial Bold" , 20), anchor = CENTER , bg='red')
l1.place(x= 80 , y= 20)
l2 = Label(text ="Location" , font=("Arial Bold" , 15) , bg = 'snow')
l2.place(x= 80 , y= 100)
e1 = ttk.Combobox(font =("Arial Bold" , 11),textvariable =a)
e1['values'] =(

            '1st Block Jayanagar',
            '1st Phase JP Nagar',
            '2nd Phase Judicial Layout',
            '2nd Stage Nagarbhavi',
            '5th Block Hbr Layout',
            '5th Phase JP Nagar',
            '6th Phase JP Nagar',
            '7th Phase JP Nagar',
            '8th Phase JP Nagar',
            '9th Phase JP Nagar',
            'AECS Layout',
            'Abbigere',
            'Akshaya Nagar',
            'Ambalipura',
            'Ambedkar Nagar',
            'Amruthahalli',
            'Anandapura',
            'Ananth Nagar',
            'Anekal',
            'Anjanapura',
            'Ardendale',
            'Arekere',
            'Attibele',
            'BTM 2nd Stage',
            'BTM Layout',
            'Babusapalaya',
            'Badavala Nagar',
            'Balagere',
            'Banashankari',
            'Banashankari Stage II',
            'Banashankari Stage III',
            'Banashankari Stage V',
            'Banashankari Stage VI',
            'Banaswadi',
            'Banjara Layout',
            'Bannerghatta',
            'Bannerghatta Road',
            'Basavangudi',
            'Basaveshwara Nagar',
            'Battarahalli',
            'Begur',
            'Begur Road',
            'Bellandur',
            'Benson Town',
            'Bharathi Nagar',
            'Bhoganhalli',
            'Billekahalli',
            'Binny Pete',
            'Bisuvanahalli',
            'Bommanahalli',
            'Bommasandra',
            'Bommasandra Industrial Area',
            'Bommenahalli',
            'Brookefield',
            'Budigere',
            'CV Raman Nagar',
            'Chamrajpet',
            'Chandapura',
            'Channasandra',
            'Chikka Tirupathi',
            'Chikkabanavar',
            'Chikkalasandra',
            'Choodasandra',
            'Cooke Town',
            'Cox Town',
            'Cunningham Road',
            'Dasanapura',
            'Dasarahalli',
            'Devanahalli',
            'Devarachikkanahalli',
            'Dodda Nekkundi',
            'Doddaballapur',
            'Doddakallasandra',
            'Doddathoguru',
            'Domlur',
            'Dommasandra',
            'EPIP Zone',
            'Electronic City',
            'Electronic City Phase II',
            'Electronics City Phase 1',
            'Frazer Town',
            'GM Palaya',
            'Garudachar Palya',
            'Giri Nagar',
            'Gollarapalya Hosahalli',
            'Gottigere',
            'Green Glen Layout',
            'Gubbalala',
            'Gunjur',
            'HAL 2nd Stage',
            'HBR Layout',
            'HRBR Layout',
            'HSR Layout',
            'Haralur Road',
            'Harlur',
            'Hebbal',
            'Hebbal Kempapura',
            'Hegde Nagar',
            'Hennur',
            'Hennur Road',
            'Hoodi',
            'Horamavu Agara',
            'Horamavu Banaswadi',
            'Hormavu',
            'Hosa Road',
            'Hosakerehalli',
            'Hoskote',
            'Hosur Road',
            'Hulimavu',
            'ISRO Layout',
            'ITPL',
            'Iblur Village',
            'Indira Nagar',
            'JP Nagar',
            'Jakkur',
            'Jalahalli',
            'Jalahalli East',
            'Jigani',
            'Judicial Layout',
            'KR Puram',
            'Kadubeesanahalli',
            'Kadugodi',
            'Kaggadasapura',
            'Kaggalipura',
            'Kaikondrahalli',
            'Kalena Agrahara',
            'Kalyan nagar',
            'Kambipura',
            'Kammanahalli',
            'Kammasandra',
            'Kanakapura',
            'Kanakpura Road',
            'Kannamangala',
            'Karuna Nagar',
            'Kasavanhalli',
            'Kasturi Nagar',
            'Kathriguppe',
            'Kaval Byrasandra',
            'Kenchenahalli',
            'Kengeri',
            'Kengeri Satellite Town',
            'Kereguddadahalli',
            'Kodichikkanahalli',
            'Kodigehaali',
            'Kodigehalli',
            'Kodihalli',
            'Kogilu',
            'Konanakunte',
            'Koramangala',
            'Kothannur',
            'Kothanur',
            'Kudlu',
            'Kudlu Gate',
            'Kumaraswami Layout',
            'Kundalahalli',
            'LB Shastri Nagar',
            'Laggere',
            'Lakshminarayana Pura',
            'Lingadheeranahalli',
            'Magadi Road',
            'Mahadevpura',
            'Mahalakshmi Layout',
            'Mallasandra',
            'Malleshpalya',
            'Malleshwaram',
            'Marathahalli',
            'Margondanahalli',
            'Marsur',
            'Mico Layout',
            'Munnekollal',
            'Murugeshpalya',
            'Mysore Road',
            'NGR Layout',
            'NRI Layout',
            'Nagarbhavi',
            'Nagasandra',
            'Nagavara',
            'Nagavarapalya',
            'Narayanapura',
            'Neeladri Nagar',
            'Nehru Nagar',
            'OMBR Layout',
            'Old Airport Road',
            'Old Madras Road',
            'Padmanabhanagar',
            'Pai Layout',
            'Panathur',
            'Parappana Agrahara',
            'Pattandur Agrahara',
            'Poorna Pragna Layout',
            'Prithvi Layout',
            'R.T. Nagar',
            'Rachenahalli',
            'Raja Rajeshwari Nagar',
            'Rajaji Nagar',
            'Rajiv Nagar',
            'Ramagondanahalli',
            'Ramamurthy Nagar',
            'Rayasandra',
            'Sahakara Nagar',
            'Sanjay nagar',
            'Sarakki Nagar',
            'Sarjapur',
            'Sarjapur  Road',
            'Sarjapura - Attibele Road',
            'Sector 2 HSR Layout',
            'Sector 7 HSR Layout',
            'Seegehalli',
            'Shampura',
            'Shivaji Nagar',
            'Singasandra',
            'Somasundara Palya',
            'Sompura',
            'Sonnenahalli',
            'Subramanyapura',
            'Sultan Palaya',
            'TC Palaya',
            'Talaghattapura',
            'Thanisandra',
            'Thigalarapalya',
            'Thubarahalli',
            'Thyagaraja Nagar',
            'Tindlu',
            'Tumkur Road',
            'Ulsoor',
            'Uttarahalli',
            'Varthur',
            'Varthur Road',
            'Vasanthapura',
            'Vidyaranyapura',
            'Vijayanagar',
            'Vishveshwarya Layout',
            'Vishwapriya Layout',
            'Vittasandra',
            'Whitefield',
            'Yelachenahalli',
            'Yelahanka',
            'Yelahanka New Town',
            'Yelenahalli',
            'Yeshwanthpur',
            'other'
 )
e1.place(x = 250 , y= 100)
l3 = Label(text ="Total Sqr Feet" , font=("Arial Bold" ,15) , bg='snow')
l3.place(x= 80 , y= 140)
e2 = Entry(font =20 , bd=5 , textvariable = b)
e2.place(x = 250 , y= 140)
l4 = Label(text ="No. of Bathroom" , font=("Arial Bold" ,15), bg='snow')
l4.place(x= 80 , y= 180)
e3 = Entry(font =20 , bd=5 , textvariable = c)
e3.place(x = 250 , y= 180)
l5 = Label(text ="No. of BHK" , font=("Arial Bold" ,15), bg='snow')
l5.place(x= 80 , y= 220)
e4 = Entry(font =20 , bd=5 , textvariable = d)
e4.place(x = 250 , y= 220)

b1 = Button(text = "Prediction", bd=5 , bg= "red" , command = predict)
b1.place(x = 240 , y=260)

l5 = Label(text ="predicted Price of Home = " , font=("Arial Bold" ,10), bg='snow')
l5.place(x= 100 , y= 320)


 
           
t.mainloop()
